Task jdp200902 2
hubert-ros/project-jdp-2009-02 pull request #1
Opened 2020-09-21 17:25 UTC by marcinPluciennik

2020-09-21 19:38 UTC, lastrider approved these changes

2020-09-22 12:16 UTC, hubert-ros requested changes

2020-09-22 12:16 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public String getGroup(){
Według opisu modułu mamy wyświetlać grupe o podanym id. Ta metoda powinna przyjmować jakieś id. Najlepiej będzie je umieścić w path

2020-09-22 12:16 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public String updateGroup(){
To samo co wyżej z tą różnicą, że powinien być przyjmowany jakiś obiekt w body

2020-09-23 08:27 UTC, hubert-ros approved these changes

2020-09-23 08:33 UTC, merged