Jdp200902 12
hubert-ros/project-jdp-2009-02 pull request #10
Opened 2020-09-30 17:53 UTC by mzieniewicz

Utworzyłam dodatkowy konstruktor w klasie ProductDto (4 argumenty), aby klasa ProductController się nie wysypywała.

2020-10-01 06:50 UTC, Wojciech-Sak89 requested changes

2020-10-01 06:50 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Group group;
Umieszczanie "cascade = CascadeType.ALL" jest tu niewskazane. Usunięcie danego Product spowoduje usunięcie Cart, Order i Group z nim związanych

2020-10-01 06:50 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
Przydałoby się pole "private int amount", które pokaże ile egzemplarzy produktu jest na stanie.

2020-10-01 06:50 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/dao/ProductDao.java
> +import javax.transaction.Transactional;
lepiej zmienić ten import na "import org.springframework.transaction.annotation.Transactional;", z Marcinem uznaliśmy, że lepiej trzymać się tego rozwiązania dla ujednolicenia

2020-10-01 06:50 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      private String description;
Trzeba po tej stronie relacji dodać odniesienie do Product z adnotacją `@OneToMany` z listą produktów (zerknij do Gliffy), podobnie z  resztą relacji `@ManyToOne`, które są w Product (Cart i Order)), jeżeli w nich brakuje

2020-10-01 06:54 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
>  public class ProductDto {
Zmiana tej klasy w tym tasku nie była potrzebna.

2020-10-01 06:55 UTC, hubert-ros approved these changes

2020-10-01 06:57 UTC, hubert-ros requested changes
Wojtek ma dobre uwagi. Trzeba poprawić to o czym wspomniał

2020-10-01 11:50 UTC, mzieniewicz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
Zastanawiałam sie nad tym ale w przypadku butów czy ubrań z reguły widzisz tylko czy dana rzecz jest dostępna. Wydaje mi się ze sama ilość produktów i  ich dostępność  powinna być w jakieś innej klasie (powiazanej ze stanem magazynu itp.). Nie wiem czy to nie za dużo dla jednej klasy.

2020-10-01 11:58 UTC, mzieniewicz commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      private String description;
Encja Cart już ma wpisaną tą zależność, nie wiem czy umieszczać relacje @OneToMany w klasach Group i Order skoro implementacja tych encji jest w innych taskach.

2020-10-01 12:19 UTC, mzieniewicz commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Group group;
Oki, rzeczywiście lepiej jak tego nie będzie. fetch = FetchType.LAZY zostawiam.

2020-10-01 12:26 UTC, mzieniewicz commented on src/main/java/com/kodilla/ecommercee/dao/ProductDao.java
> +import javax.transaction.Transactional;
W  klasie UserDto importy sa nie poprawione (i tym się zasugerowałam). Poprawiam.

2020-10-02 05:46 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
ok, to po naszej wczorajszej rozmowie dodajemy te amount, już nie będzie ta klasa taka pusta, potestujemy jakieś mnożenie BigDecimali ;)

2020-10-02 05:47 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/dao/ProductDao.java
> +import javax.transaction.Transactional;
O właśnie, możesz przy okazji zmienić w UserDao?

2020-10-02 05:52 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      private String description;
To tak jak wczoraj omawialiśmy, możesz dodać te relacje w Group i Order, nawet jeśli oprócz id miałyby być to jedyne pola w tych klasach. Taka minimalistyczna implementacja dla potrzeb encji z Twojego taska jest ok

2020-10-02 13:31 UTC, Wojciech-Sak89 approved these changes

2020-10-02 19:43 UTC, hubert-ros approved these changes

2020-10-03 09:35 UTC, merged