Jdp200902 13 encja group
hubert-ros/project-jdp-2009-02 pull request #13
Opened 2020-10-04 10:17 UTC by gothamloop

2020-10-05 14:29 UTC, Wojciech-Sak89 requested changes

2020-10-05 14:29 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
productList przyda się zainicjalizować

2020-10-05 16:00 UTC, gothamloop commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Czy konieczna jest faktycznie ta inicjalizacja?

2020-10-05 16:12 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Listę trzeba zainicjalizować albo w konstruktorze albo od razu po deklaracji. 

Być może lombok inicjalizuje listę przez @AllArgsConstructor, ale tworząc samemu nowy obiekt nie korzystasz ze wszystkich argumentów - nie dodajesz ręcznie id bo jest auto-increment, więc na którymś etapie będzie potrzebny konstruktor nie obejmujący wszystkich argumentów. (Np. pisania testów encji, co akurat mam za sobą :)) 

Raczej chcemy minimalizować liczbę argumentów w takim nowym konstruktorze, więc pewnie obejmą pola String nameGroup i String description, a dodanie czegoś do listy productList odbędzie się przez getter.

 A więc tak, trzeba zainicjalizować, bo nie uda się nic dodać przez ten getter.

2020-10-05 18:34 UTC, gothamloop commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Jak to najprościej zainicjalizować aby nie rozbudowywać nie wiadomo jak kodu?

2020-10-06 05:00 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
private List<Product> productsList = new ArrayList<>();

2020-10-06 06:15 UTC, gothamloop commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Ale ja to miałem w kodzie.

2020-10-06 06:18 UTC, gothamloop commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Zmiana wprowadzona

2020-10-06 07:53 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
ok, robię approve, ale poczekaj przed mergem na komentarze Huberta :)

2020-10-06 07:54 UTC, Wojciech-Sak89 approved these changes

2020-10-06 09:05 UTC, hubert-ros approved these changes

2020-10-06 09:05 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
>      @OneToMany(
Tak, listy w encjach lepiej inicjalizować

2020-10-06 09:51 UTC, merged