Jdp200902 31
hubert-ros/project-jdp-2009-02 pull request #15
Opened 2020-10-04 20:34 UTC by lastrider

2020-10-05 14:37 UTC, Wojciech-Sak89 submitted a review, later dismissed

2020-10-05 14:37 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products;
przyda się inicjalizacja tej zmiennej

2020-10-05 14:37 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Date created;
W sumie pytanie do Huberta, lepiej Date czy LocalDate? Ja byłbym jednaj za LocalDate, jest bardziej elastyczny. Dlaczego zmieniłeś na Date?

2020-10-05 18:32 UTC, mzieniewicz approved these changes

2020-10-06 09:07 UTC, hubert-ros requested changes

2020-10-06 09:07 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products;
+1

2020-10-06 09:07 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Date created;
Lepiej LocalDate, bo jest nowsze

2020-10-06 09:15 UTC, hubert-ros requested changes
Skoro jest to implementacja do buga Jdp200902 31 to w tym PR powinien znaleźć się tylko kod związany z poprawką tego buga. Czyli tylko klasa User

2020-10-08 09:07 UTC, hubert-ros approved these changes

2020-10-08 16:33 UTC, merged