JDP200902-17 Encja Product - Testy
hubert-ros/project-jdp-2009-02 pull request #16
Opened 2020-10-06 16:40 UTC by marcinPluciennik

2020-10-07 06:07 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        //Than
"Then", nie "than" :)

2020-10-07 06:18 UTC, Wojciech-Sak89 requested changes

2020-10-07 06:18 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +    public void testProductDaoSave(){
Przydałyby się testy sprawdzające poprawności zapisywania Product z obiektami, Cart, Order i Group, które są jego częścią.

2020-10-07 06:18 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        productDao.deleteById(id);
możesz sekcję `Then` wstawić do try (oprócz `long id = product1.getId();` ), a `CleanUp` do `finally`
```
//Then
try {

//CleanUp
} finally {
}
```
Hubert mi cos takiego sugerował, żeby mieć pewność, że jak się cos po drodze wysypie, to CelanUp zadziała.

2020-10-07 08:27 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        //Than
ok :) poprawię

2020-10-07 08:30 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +    public void testProductDaoSave(){
W swoim teście robiłeś test na zapisywanie produktów w encji Cart. Więc czy te testy właśnie nie powinny się znaleźć odpowiednio w encjach Cart, Order i Group?

2020-10-07 08:30 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        productDao.deleteById(id);
ok , poprawię

2020-10-07 08:54 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +    public void testProductDaoSave(){
Wydaje mi się tylko, że warto przetestować zapis Product ze wszystkimi jego polami.

Może to być prosty test negatywny, który przetestuje pełne utworzenie obiektu Product z wszystkimi polami. 
Negatywny w sensie sprawdzenia, czy zapisanie takiego pełnego Product nie utworzy czasem Cart, Order i Group, bo nie ma po swojej stronie `CascadeType.ALL` (a przynajmniej tego bym się spodziewał).

2020-10-07 09:00 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +    public void testProductDaoSave(){
Ale tak, w sumie też wydaje mi się, że powinien być i taki test z wykorzystaniem *Dao save Cart, Order i Group* z odniesieniem do Twojego Product, ale na końcu sprawdzasz ich obecność wyciągając z bazy dany Product.

2020-10-07 09:06 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +    public void testProductDaoSave(){
Ale póki tamte wszystkie nie mają przetestowane save, to wydaje mi się, że możesz spróbować tylko dodać ten test negatywny bez Dao save: Cart, Order i Group. Jestem ciekawy co na to inni.

2020-10-08 05:33 UTC, Wojciech-Sak89 requested changes

2020-10-08 05:33 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        Group group = new Group();
Jeszcze trzeba zaznaczyć, że te obiekty przypisują sobie product setterami albo przez getter do ich listy produktów

2020-10-08 14:30 UTC, hubert-ros requested changes

2020-10-08 14:30 UTC, hubert-ros commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +@Transactional
Gdy masz tą adnotacje to nie musisz robić fazy //CleanUp

2020-10-09 14:41 UTC, Wojciech-Sak89 requested changes

2020-10-09 14:41 UTC, wojciech-sak commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public Product(String name, String description, BigDecimal price, int amount, Cart cart, Order order, Group group) {
Wystarczą same settery, które dodałeś dla  Cart, Order i Group. Lepiej ograniczyć ten konstruktor do tego: 
`public Product(String name, String description, BigDecimal price, int amount)`

2020-10-09 14:41 UTC, wojciech-sak commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        try {
w tym teście usunięcie try-finally i sekcji //CleanUp powinno odbyć się bez zakłóceń, spróbuj uruchomić tylko ten test po usunięciu  try-finally i //CleanUp

2020-10-09 14:41 UTC, wojciech-sak commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        product.setGroup(group);
Przypisujesz produktowi pola cart, order i group albo przez konstruktor, albo setterami, tak robisz dwa razy to samo :) Tak jak pisałem wcześniej ogranicz ten konstruktor i zostaw settery

2020-10-09 14:41 UTC, wojciech-sak commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +            long groupId = group.getId();
oczekujesz, że `long` będzie zawierało null, ale typ primitywny nie może byc null, tylko obiekt, więc trzeba zmienić na `Long`

2020-10-09 15:40 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        Group group = new Group();
Nie wiem czy do końca to czuję :) tak ma być? : https://github.com/hubert-ros/project-jdp-2009-02/pull/16/commits/f002d7078de06e5cec02ccd3a0ab153c1570aa93

2020-10-12 06:58 UTC, hubert-ros requested changes

2020-10-12 06:58 UTC, hubert-ros commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        productDao.deleteById(id);
Usuń to i testy dalej będą przechodzić

2020-10-12 06:58 UTC, hubert-ros commented on src/test/java/com/kodilla/ecommercee/dao/ProductDaoTestSuite.java
> +        productDao.deleteById(id);
Usuń to i testy dalej będą przechodzić

2020-10-12 13:27 UTC, hubert-ros approved these changes

2020-10-12 13:47 UTC, wojciech-sak approved these changes

2020-10-12 13:47 UTC, merged