JDP200902-23 CartController - rzeczywista implementacja metod
hubert-ros/project-jdp-2009-02 pull request #17
Opened 2020-10-07 11:03 UTC by Wojciech-Sak89

Na potrzeby implementacji utworzyłem stuby wszystkich mapperów, do tego była też potrzebna adnotacja @NoArgsConstructor we wszystkich Dtos.

Z ciekawych rzeczy: żeby uniknąć potencjalnego StackOverflow przy mapowaniu (mam na myśli wszystkie mappery wszystkich klas, mogłyby się zapętlić jeśli w kółko odwoływałyby się do siebie przy mapowaniu), w `CartDto` zamiast `List<ProductDto> productsDtos`    dałem `List<Long> productsIds`. 
Wtedy mapowanie wymaga korzystania z bazy danych. Trochę wymagające, ale polecam praktykę :)

Dodałem też `testFindProductsList_ByCart_Id()`, bo dodałem metodę do ProductDao.

2020-10-08 14:29 UTC, hubert-ros requested changes

2020-10-08 14:29 UTC, hubert-ros commented on src/test/java/com/kodilla/ecommercee/dao/CartDaoTestSuite.java
> +@Transactional
Gdy jest ta adnotacja to nie trzeba robić fazy //CleanUp. Musisz zdecydować się na jedno podejście

2020-10-08 16:02 UTC, marcinPluciennik approved these changes

2020-10-09 05:53 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/CartDaoTestSuite.java
> +@Transactional
ok, usunąłem try-finally

2020-10-09 06:29 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/CartDaoTestSuite.java
> +@Transactional
ok, poprawione, już jest bez CleanUpów

2020-10-09 06:33 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/CartDaoTestSuite.java
> +@Transactional
puściłem testy i jest ok

2020-10-09 06:48 UTC, mzieniewicz approved these changes

2020-10-09 15:42 UTC, hrosinski approved these changes

2020-10-09 15:43 UTC, hrosinski approved these changes

2020-10-09 15:43 UTC, hubert-ros approved these changes

2020-10-09 15:57 UTC, hubert-ros requested changes

2020-10-09 15:57 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        order.getProductsList().addAll(cart.getProductsList());
Dopiero teraz mi to wpadło w oko. Nie powinniśmy dodawać w ten sposób rzeczy do listy. W tym przypadku powinieneś użyć settera. Jeżeli chcesz coś dodać do listy kiedy już tam coś jest to należy pobrać listę getterem, utworzyć jej kopię, dodać elementy do kopii, a później za pomocą settera ustawić kopię jako listę

2020-10-09 16:26 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        order.getProductsList().addAll(cart.getProductsList());
Ale przecież w liście produktów w zawartej w Order właśnie nic nie ma, to świeżo utworzony obiekt. 

Metodę `createOrder(Long cartId, Long userId)` rozumiem jako finalizację zakupów, stworzenie zamówienia. 

Wcześniej mogliśmy utworzyć koszyk, dodać do niego produkty innymi metodami z kontrolera, a ta metoda, po tym jak mamy już gotowy koszyk, to podajemy jego cartId oraz  userid, żeby sfinalizować transakcję i utworzyć nowy Order.

2020-10-11 17:25 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        order.getProductsList().addAll(cart.getProductsList());
Skoro nic nie ma to można użyć settera i dać order.setProductsList(cart.getProductsList());. Można też utworzyć metodę addProduct czy coś w tym stylu. Chodzi mi oczywiście tylko o tą linijke z dodawniaem produktów do listy. Takie modyfikacjie obiektów jak teraz w kodzie nie są zbyt eleganckie i naruszają zasadę niemodyfikowalności obiektów. Co jakby ktoś zmienił metodę `getProductsList()` na taką która będzie zwracała kopie listy produktów? Wtedy dodanie produktów w taki sposób jak teraz to robisz spowoduje, że nic się nie doda.

2020-10-12 06:20 UTC, Wojciech-Sak89 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        order.getProductsList().addAll(cart.getProductsList());
Wielkie dzięki za uwagi i wyjaśnienia, nie pomyślałem o tym w ten sposób. 
Już poprawiłem :)

2020-10-12 06:50 UTC, hubert-ros approved these changes

2020-10-12 07:05 UTC, merged