First Commit
hubert-ros/project-jdp-2009-02 pull request #18
Opened 2020-10-07 18:50 UTC by mzieniewicz

Mam problem z testami encji User - nie działają mi operacje na orderList. Są zakomentowane, ponieważ podczas wszelkich asercji sprawdzających np. size() mam komunikat: "failed to lazily initialize a collection of role: om.kodilla.ecommercee.domain.User.ordersList, could not initialize proxy - no Session."
Przy zmianie na fetch.Eager mam informacje: "Failed to load ApplicationContext java.lang.IllegalStateException: Failed to load ApplicationContext".

Mam nadzieję, że ktoś już miał podobny problem.

2020-10-08 10:03 UTC, mzieniewicz commented
Przepraszam za nazwę commita. Powinno być JDP200902-20 - testy encji user.

2020-10-08 16:46 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@SpringBootTest
Spróbuj wkleić tu @Transactional, ale nie jestem pewien :(

2020-10-08 16:47 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@SpringBootTest
Tzn @Transactional (z dużej litery) :)

2020-10-08 16:48 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@SpringBootTest
Cholera , Github sam zmienia wielkość liter:) - ma być z dużej litery

2020-10-09 06:43 UTC, Wojciech-Sak89 requested changes

2020-10-09 06:43 UTC, Wojciech-Sak89 commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +        User user = new User("Jan", "Nowak");
Chyba nie ma takiego konstruktora

2020-10-09 07:16 UTC, mzieniewicz commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@SpringBootTest
Wkleiłam @Transactional ale nie rozwiązało  to problemu.

2020-10-09 12:39 UTC, marcinPluciennik commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@SpringBootTest
Szkoda :) Hubert miał rację, musisz napisać do Huberta.

2020-10-09 17:55 UTC, mzieniewicz commented
Problem rozwiązany! Zaprasza do sprawdzenia.

2020-10-12 06:54 UTC, hubert-ros requested changes

2020-10-12 06:54 UTC, hubert-ros commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@Transactional
Mając `@Transactional` nie potrzebujesz 
```
//CleanUp
        userDao.deleteById(id);
```
Musisz zdecydować się na jedno lub drugie

2020-10-12 12:40 UTC, mzieniewicz commented on src/test/java/com/kodilla/ecommercee/dao/UserDaoTestSuite.java
> +@Transactional
Wyrzuciłam //Clean up jest tylko @Transactional

2020-10-12 17:35 UTC, marcinPluciennik approved these changes

2020-10-12 17:39 UTC, marcinPluciennik commented
Hej, przejrzałem "na szybko" jeśli przechodzą te testy to ok :) , zastanawia mnie czemu jest info, że "All checks have failed "? Buduje Ci się projekt?

2020-10-12 17:45 UTC, marcinPluciennik commented
OK, teraz jest All checks have passed :)

2020-10-13 06:40 UTC, hubert-ros approved these changes

2020-10-13 08:37 UTC, merged