JDP200902-1
hubert-ros/project-jdp-2009-02 pull request #2
Opened 2020-09-21 19:28 UTC by lastrider

2020-09-22 10:43 UTC, marcinPluciennik commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    String name;
private przy polach klasy?

2020-09-22 12:24 UTC, hubert-ros requested changes

2020-09-22 12:24 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    String name;
Tak, pola klasy powinny być prywante

2020-09-28 07:01 UTC, hubert-ros approved these changes

2020-09-28 09:02 UTC, merged