JDP200902-5_UserController
hubert-ros/project-jdp-2009-02 pull request #4
Opened 2020-09-23 09:51 UTC by gothamloop

UserController - wstępna implementacja endpointów

2020-09-24 10:35 UTC, hubert-ros requested changes

2020-09-24 10:35 UTC, hubert-ros commented on build.gradle
> +        springBootVersion = '2.0.5.RELEASE'
Dlaczego chcesz zmniejszyć wersje?

2020-09-24 10:35 UTC, hubert-ros commented on settings.gradle
> +rootProject.name = 'project-jdp-2009-02'
Nie ma potrzeby zmiany tego

2020-09-24 10:35 UTC, hubert-ros commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +    }
Ta klasa tutaj jest niepotrzbna

2020-09-24 10:35 UTC, hubert-ros commented on src/main/java/controller/TaskNotFoundException.java
> +public class TaskNotFoundException extends Exception {
Raczej powinno się to nazywać `UserNotFoundException`

2020-09-24 10:35 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +    }
Te metody są niepotrzbne. Sprawdź jakie mają być endpointy w opisie modułu.

2020-09-24 14:57 UTC, gothamloop commented on build.gradle
> +        springBootVersion = '2.0.5.RELEASE'
ok faktycznie nie potrzeba tego robić

2020-09-24 14:59 UTC, gothamloop commented on settings.gradle
> +rootProject.name = 'project-jdp-2009-02'
skąd mi sie to wzieło? szczerze przyznam, że nie widziałem

2020-09-24 15:00 UTC, gothamloop commented on src/main/java/com/kodilla/ecommercee/EcommerceeApplication.java
> +    }
usunąłem

2020-09-24 15:00 UTC, gothamloop commented on src/main/java/controller/TaskNotFoundException.java
> +public class TaskNotFoundException extends Exception {
jasne, poprawione

2020-09-24 15:01 UTC, gothamloop commented on src/main/java/controller/UserController.java
> +    }
faktycznie, rozpędziłem się a metody mają być zupełnie inne

2020-09-28 06:57 UTC, hubert-ros requested changes

2020-09-28 06:57 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +    public UserDto getUserToken(@RequestParam final Long id) throws UserNotFoundException {
Token powinien być Stringiem oraz powinien być generowany po podaniu czegoś więcej niż id. Najlepiej aby ta metoda przyjmowała obiekt mająca username i hasło.

2020-09-28 06:57 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +    public UserDto getUser(@RequestParam Long Id) throws UserNotFoundException {
W opisie modułu nie ma takiej metody. Powinna być metoda blokująca usera

2020-09-28 07:10 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +        service.saveUser(userMapper.mapToUser(userDto));
Niepotrzebnie już operujesz na bazie. To zadanie jest w innym tasku

2020-09-28 16:08 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +    public void getBlockUser(@RequestParam Long Id) throws UserNotFoundException {
Raczej powinno być blockUser, a nie getBlockUser

2020-10-01 07:01 UTC, hubert-ros requested changes

2020-10-01 07:01 UTC, hubert-ros commented on src/main/java/controller/UserController.java
> +    public String generateToken(@RequestParam String username, String password) {
Brakuje drugiego @RequestParam przy String password

2020-10-01 07:01 UTC, hubert-ros commented on src/main/java/domain/UserDto.java
> +*/
Takie komentarze trzeba usunąć

2020-10-02 08:39 UTC, hubert-ros approved these changes

2020-10-02 09:21 UTC, merged